name: hakyll
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: hakyll
        uses: docker://quay.io/ftweedal/hakyll
